a:a.cpp
	g++ -o a a.cpp -std=c++17 -O2
	./a

b:b.cpp
	g++ -o b b.cpp -std=c++17 -O2
	./b

c:c.cpp
	g++ -o c c.cpp -std=c++17 -O2 -Wall -Wextra
	./c

d:d.cpp
	g++ -o d d.cpp -std=c++17 -O2
	./d

e:e.cpp
	g++ -o e e.cpp -std=c++17 -O2
	./e

f:f.cpp
	g++ -o f f.cpp -std=c++17 -O2
	./f

g:g.cpp
	g++ -o g -std=c++17 -O2
	./g
